// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/test_schema.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	SingleNestedMessage *TestMessage_NestedMessage `protobuf:"bytes,1,opt,name=single_nested_message,json=singleNestedMessage,proto3" json:"single_nested_message,omitempty"`
	SingleInt32         int32                      `protobuf:"varint,2,opt,name=single_int32,json=singleInt32,proto3" json:"single_int32,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_internal_proto_test_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_test_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_test_schema_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetSingleNestedMessage() *TestMessage_NestedMessage {
	if x != nil {
		return x.SingleNestedMessage
	}
	return nil
}

func (x *TestMessage) GetSingleInt32() int32 {
	if x != nil {
		return x.SingleInt32
	}
	return 0
}

type TestMessage_NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bb            int64                  `protobuf:"varint,1,opt,name=bb,proto3" json:"bb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_NestedMessage) Reset() {
	*x = TestMessage_NestedMessage{}
	mi := &file_internal_proto_test_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_NestedMessage) ProtoMessage() {}

func (x *TestMessage_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_test_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_NestedMessage.ProtoReflect.Descriptor instead.
func (*TestMessage_NestedMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_test_schema_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestMessage_NestedMessage) GetBb() int64 {
	if x != nil {
		return x.Bb
	}
	return 0
}

var File_internal_proto_test_schema_proto protoreflect.FileDescriptor

const file_internal_proto_test_schema_proto_rawDesc = "" +
	"\n" +
	" internal/proto/test_schema.proto\x12\x19cel.skills.internal.proto\"\xbb\x01\n" +
	"\vTestMessage\x12h\n" +
	"\x15single_nested_message\x18\x01 \x01(\v24.cel.skills.internal.proto.TestMessage.NestedMessageR\x13singleNestedMessage\x12!\n" +
	"\fsingle_int32\x18\x02 \x01(\x05R\vsingleInt32\x1a\x1f\n" +
	"\rNestedMessage\x12\x0e\n" +
	"\x02bb\x18\x01 \x01(\x03R\x02bbB2Z0github.com/cel-expr/skills/internal/proto;testpbb\x06proto3"

var (
	file_internal_proto_test_schema_proto_rawDescOnce sync.Once
	file_internal_proto_test_schema_proto_rawDescData []byte
)

func file_internal_proto_test_schema_proto_rawDescGZIP() []byte {
	file_internal_proto_test_schema_proto_rawDescOnce.Do(func() {
		file_internal_proto_test_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_test_schema_proto_rawDesc), len(file_internal_proto_test_schema_proto_rawDesc)))
	})
	return file_internal_proto_test_schema_proto_rawDescData
}

var file_internal_proto_test_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_test_schema_proto_goTypes = []any{
	(*TestMessage)(nil),               // 0: cel.skills.internal.proto.TestMessage
	(*TestMessage_NestedMessage)(nil), // 1: cel.skills.internal.proto.TestMessage.NestedMessage
}
var file_internal_proto_test_schema_proto_depIdxs = []int32{
	1, // 0: cel.skills.internal.proto.TestMessage.single_nested_message:type_name -> cel.skills.internal.proto.TestMessage.NestedMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_test_schema_proto_init() }
func file_internal_proto_test_schema_proto_init() {
	if File_internal_proto_test_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_test_schema_proto_rawDesc), len(file_internal_proto_test_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_test_schema_proto_goTypes,
		DependencyIndexes: file_internal_proto_test_schema_proto_depIdxs,
		MessageInfos:      file_internal_proto_test_schema_proto_msgTypes,
	}.Build()
	File_internal_proto_test_schema_proto = out.File
	file_internal_proto_test_schema_proto_goTypes = nil
	file_internal_proto_test_schema_proto_depIdxs = nil
}
