// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: internal/proto/test_schema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state                          protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_SingleNestedMessage *TestMessage_NestedMessage `protobuf:"bytes,1,opt,name=single_nested_message,json=singleNestedMessage"`
	xxx_hidden_SingleInt32         int32                      `protobuf:"varint,2,opt,name=single_int32,json=singleInt32"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_internal_proto_test_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_test_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestMessage) GetSingleNestedMessage() *TestMessage_NestedMessage {
	if x != nil {
		return x.xxx_hidden_SingleNestedMessage
	}
	return nil
}

func (x *TestMessage) GetSingleInt32() int32 {
	if x != nil {
		return x.xxx_hidden_SingleInt32
	}
	return 0
}

func (x *TestMessage) SetSingleNestedMessage(v *TestMessage_NestedMessage) {
	x.xxx_hidden_SingleNestedMessage = v
}

func (x *TestMessage) SetSingleInt32(v int32) {
	x.xxx_hidden_SingleInt32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TestMessage) HasSingleNestedMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SingleNestedMessage != nil
}

func (x *TestMessage) HasSingleInt32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TestMessage) ClearSingleNestedMessage() {
	x.xxx_hidden_SingleNestedMessage = nil
}

func (x *TestMessage) ClearSingleInt32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SingleInt32 = 0
}

type TestMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SingleNestedMessage *TestMessage_NestedMessage
	SingleInt32         *int32
}

func (b0 TestMessage_builder) Build() *TestMessage {
	m0 := &TestMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SingleNestedMessage = b.SingleNestedMessage
	if b.SingleInt32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_SingleInt32 = *b.SingleInt32
	}
	return m0
}

type TestMessage_NestedMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bb          int64                  `protobuf:"varint,1,opt,name=bb"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TestMessage_NestedMessage) Reset() {
	*x = TestMessage_NestedMessage{}
	mi := &file_internal_proto_test_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_NestedMessage) ProtoMessage() {}

func (x *TestMessage_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_test_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestMessage_NestedMessage) GetBb() int64 {
	if x != nil {
		return x.xxx_hidden_Bb
	}
	return 0
}

func (x *TestMessage_NestedMessage) SetBb(v int64) {
	x.xxx_hidden_Bb = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TestMessage_NestedMessage) HasBb() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TestMessage_NestedMessage) ClearBb() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Bb = 0
}

type TestMessage_NestedMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bb *int64
}

func (b0 TestMessage_NestedMessage_builder) Build() *TestMessage_NestedMessage {
	m0 := &TestMessage_NestedMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Bb != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Bb = *b.Bb
	}
	return m0
}

var File_internal_proto_test_schema_proto protoreflect.FileDescriptor

const file_internal_proto_test_schema_proto_rawDesc = "" +
	"\n" +
	" internal/proto/test_schema.proto\x12\x19cel.skills.internal.proto\"\xbb\x01\n" +
	"\vTestMessage\x12h\n" +
	"\x15single_nested_message\x18\x01 \x01(\v24.cel.skills.internal.proto.TestMessage.NestedMessageR\x13singleNestedMessage\x12!\n" +
	"\fsingle_int32\x18\x02 \x01(\x05R\vsingleInt32\x1a\x1f\n" +
	"\rNestedMessage\x12\x0e\n" +
	"\x02bb\x18\x01 \x01(\x03R\x02bbB5Z3google3/third_party/cel/skills/internal/proto;protob\beditionsp\xe9\a"

var file_internal_proto_test_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_test_schema_proto_goTypes = []any{
	(*TestMessage)(nil),               // 0: cel.skills.internal.proto.TestMessage
	(*TestMessage_NestedMessage)(nil), // 1: cel.skills.internal.proto.TestMessage.NestedMessage
}
var file_internal_proto_test_schema_proto_depIdxs = []int32{
	1, // 0: cel.skills.internal.proto.TestMessage.single_nested_message:type_name -> cel.skills.internal.proto.TestMessage.NestedMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_test_schema_proto_init() }
func file_internal_proto_test_schema_proto_init() {
	if File_internal_proto_test_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_test_schema_proto_rawDesc), len(file_internal_proto_test_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_test_schema_proto_goTypes,
		DependencyIndexes: file_internal_proto_test_schema_proto_depIdxs,
		MessageInfos:      file_internal_proto_test_schema_proto_msgTypes,
	}.Build()
	File_internal_proto_test_schema_proto = out.File
	file_internal_proto_test_schema_proto_goTypes = nil
	file_internal_proto_test_schema_proto_depIdxs = nil
}
